### ISSUE TITLE
Java out of memory error with excess memory 

### ISSUE THREAD

**Issue by Artifice120** [trinityrnaseq/trinityrnaseq#1421]
I seem to be getting an out of memory error with the following command using singularity image.

```
#!/bin/bash
#SBATCH -J TRINITY_test
#SBATCH --account ACF-UTK0011
#SBATCH --time 24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=48
#SBATCH --partition=campus-bigmem
#SBATCH --output=tlog/Tt.o%j
#SBATCH --error=terror/Tt.e%j
#SBATCH --exclusive
#SBATCH --qos=campus-bigmem

cd /lustre/isaac/scratch/jtorre28/Treg

singularity exec -H /tmp -e trinityrnaseq.v2.15.1.simg Trinity --seqType fa --single /lustre/isaac/scratch/jtorre28/UE-map/mapreads_Enterobacterales.fa --max_memory 1000G --CPU 15
```

This partition/node has a few thousand Gigabytes of memory/RAM so I am not sure how I am getting a out of memory error even toned down to 15 CPU's.

```
warning, cmd: java -Xmx10G -Xms1G -Xss1G   -XX:ParallelGCThreads=2  -jar /usr/local/bin/Butterfly/Butterfly.jar -N 100000 -L 200 -F 500 -C /lustre/isaac/scratch/jtorre28/Treg/trinity_out_dir/read_partitions/Fb_0/CBin_0/c103.trinity.reads.fa.out/chrysalis/Component_bins/Cbin0/c0.graph  --path_reinforcement_distance=25  --NO_EM_REDUCE  failed with ret: 256, going to retry.
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at jaligner.NeedlemanWunschGotohBanded.align(NeedlemanWunschGotohBanded.java:106)
        at NWalign.run_NW_banded_alignment(NWalign.java:178)
        at TransAssembly_allProbPaths.updatePathRecursively(TransAssembly_allProbPaths.java:13783)
        at TransAssembly_allProbPaths.findPathInGraph(TransAssembly_allProbPaths.java:13570)
        at TransAssembly_allProbPaths.readAndMapSingleRead(TransAssembly_allProbPaths.java:13489)
        at TransAssembly_allProbPaths.getReadStarts(TransAssembly_allProbPaths.java:13351)
        at TransAssembly_allProbPaths.main(TransAssembly_allProbPaths.java:937)
warning, cmd: java -Xmx10G -Xms1G -Xss1G   -XX:ParallelGCThreads=2  -jar /usr/local/bin/Butterfly/Butterfly.jar -N 100000 -L 200 -F 500 -C /lustre/isaac/scratch/jtorre28/Treg/trinity_out_dir/read_partitions/Fb_0/CBin_0/c103.trinity.reads.fa.out/chrysalis/Component_bins/Cbin0/c0.graph  --path_reinforcement_distance=25  --NO_EM_REDUCE  failed with ret: 256, going to retry.

--->

Trinity run failed. Must investigate error above.
warning, cmd: /usr/local/bin/util/support_scripts/../../Trinity --single "/lustre/isaac/scratch/jtorre28/Treg/trinity_out_dir/read_partitions/Fb_0/CBin_0/c103.trinity.reads.fa" --output "/lustre/isaac/scratch/jtorre28/Treg/trinity_out_dir/read_partitions/Fb_0/CBin_0/c103.trinity.reads.fa.out" --CPU 1 --max_memory 1G --seqType fa --trinity_complete --full_cleanup --no_salmon   failed with ret: 65280, going to retry.^Msucceeded(47324), failed(1)   100% completed.

We are sorry, commands in file: [FailedCommands] failed.  :-(

Error, cmd: /usr/local/bin/trinity-plugins/BIN/ParaFly -c recursive_trinity.cmds -CPU 15 -v -shuffle  died with ret 256 at /usr/local/bin/Trinity line 2919.
        main::process_cmd("/usr/local/bin/trinity-plugins/BIN/ParaFly -c recursive_trini"...) called at /usr/local/bin/Trinity line 3653
        main::run_partitioned_cmds("recursive_trinity.cmds") called at /usr/local/bin/Trinity line 2528
        main::run_recursive_trinity("/lustre/isaac/scratch/jtorre28/Treg/trinity_out_dir/chrysalis"...) called at /usr/local/bin/Trinity line 2271
        main::run_chrysalis("/lustre/isaac/scratch/jtorre28/Treg/trinity_out_dir/inchworm."..., "/lustre/isaac/scratch/jtorre28/Treg/trinity_out_dir/single.fa", 200, 500, undef, "/lustre/isaac/scratch/jtorre28/Treg/trinity_out_dir/single.fa", "/lustre/isaac/scratch/jtorre28/Treg/trinity_out_dir/single.fa") called at /usr/local/bin/Trinity line 1895
        main::run_Trinity() called at /usr/local/bin/Trinity line 1500
        eval {...} called at /usr/local/bin/Trinity line 1499

Trinity run failed. Must investigate error above.
```

**Comment by Artifice120** [comment]
created files

![image](https://github.com/trinityrnaseq/trinityrnaseq/assets/160672410/a4f41a0c-309c-4010-a112-1d29ae18ab02)

**Comment by Artifice120** [comment]
Version  2.15.2 seems to fix this issue by limiting the max memory to only 200Gb
